In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


train test split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling

In [7]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [8]:
X_train

array([[ 0.26063395, -0.88789728,  0.23733928, ...,  0.36574167,
         0.08533153, -0.01792739],
       [-0.56628579, -0.07879376, -0.60951001, ..., -0.95648373,
        -0.02986484, -0.1780141 ],
       [ 0.36470208,  0.84248635,  0.34935639, ...,  0.51321305,
        -0.53423813, -0.89811741],
       ...,
       [-0.32721035, -0.69218492, -0.37040441, ..., -0.47879807,
         0.19430107, -0.82868913],
       [-0.62816413, -0.12652848, -0.55777847, ...,  0.6196357 ,
         2.89830235,  3.22856227],
       [ 0.27188456, -0.59432875,  0.28947815, ..., -0.18309514,
        -1.12423035,  0.08937087]])

In [9]:
X_test

array([[-0.14438796, -1.27216178, -0.12355945, ..., -0.34881041,
         0.25812609, -0.12407808],
       [ 0.61221547,  0.06679714,  0.74039791, ...,  0.96778979,
         0.65197313,  0.42618413],
       [-0.88130283, -0.15278258, -0.864909  , ..., -0.53170533,
        -1.00903398, -0.37941352],
       ...,
       [ 0.20438091, -0.37474903,  0.1733877 , ..., -0.46769971,
         1.09096471, -0.63589653],
       [-0.96286974,  1.42962341, -0.96185471, ..., -0.79791399,
         0.79363354, -0.1412917 ],
       [ 1.7035245 ,  2.15280443,  1.61209463, ...,  0.74430223,
        -0.50933081, -1.00771083]])

In [10]:
y_train

,diagnosis
227,B
346,B
91,M
191,B
373,M
...,...
138,M
53,M
195,B
31,M


Label Encoding

In [11]:
encoder = LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,

Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor=torch.from_numpy(X_train).float()
X_test_tensor=torch.from_numpy(X_test).float()
y_train_tensor=torch.from_numpy(y_train).float()
y_test_tensor=torch.from_numpy(y_test).float()

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [17]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [18]:
train_dataset=CustomDataset(X_train_tensor,y_train_tensor)
test_dataset=CustomDataset(X_test_tensor,y_test_tensor)

In [19]:
train_dataset[10]

(tensor([-1.2084, -0.5347, -1.1863, -1.0061,  0.5035, -0.3840, -0.5625, -0.7882,
         -0.8387,  1.0898, -0.0152,  0.3830, -0.0663, -0.3674,  2.2045,  0.1965,
         -0.1576, -0.2526,  1.4591,  0.3332, -1.0562, -0.6798, -1.0323, -0.8766,
          0.6217, -0.4963, -0.6753, -0.9198, -0.5700,  0.0429]),
 tensor(0.))

In [20]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32,shuffle=True)

Defining the Model

In [21]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out

Important Parameters

In [22]:
learning_rate=0.1
epochs=25

In [23]:
# create model
model=MySimpleNN(X_train_tensor.shape[1])
model.float()

# define optimizer
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

#define loss function
loss_function=nn.BCELoss()

Training Pipeline

In [24]:
# define loop
for epoch in range(epochs):

  for batch_features,batch_labels in train_loader:

    # forward pass
    y_pred=model(batch_features)

    # loss calculate
    loss=loss_function(y_pred,batch_labels.view(-1,1))

    #clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

    # print loss
    print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6198804378509521
Epoch: 1, Loss: 0.4969080984592438
Epoch: 1, Loss: 0.38201019167900085
Epoch: 1, Loss: 0.3709571957588196
Epoch: 1, Loss: 0.28721854090690613
Epoch: 1, Loss: 0.3422558307647705
Epoch: 1, Loss: 0.3489885628223419
Epoch: 1, Loss: 0.3043878674507141
Epoch: 1, Loss: 0.3398083448410034
Epoch: 1, Loss: 0.28724172711372375
Epoch: 1, Loss: 0.2400166392326355
Epoch: 1, Loss: 0.25901055335998535
Epoch: 1, Loss: 0.25638824701309204
Epoch: 1, Loss: 0.2036258727312088
Epoch: 1, Loss: 0.18340015411376953
Epoch: 2, Loss: 0.23272021114826202
Epoch: 2, Loss: 0.18573755025863647
Epoch: 2, Loss: 0.21416522562503815
Epoch: 2, Loss: 0.17699453234672546
Epoch: 2, Loss: 0.21102875471115112
Epoch: 2, Loss: 0.1304021030664444
Epoch: 2, Loss: 0.15336669981479645
Epoch: 2, Loss: 0.2074975222349167
Epoch: 2, Loss: 0.18597812950611115
Epoch: 2, Loss: 0.13576897978782654
Epoch: 2, Loss: 0.17991292476654053
Epoch: 2, Loss: 0.1918739527463913
Epoch: 2, Loss: 0.1991063952445984
Epoch

Evaluation

In [28]:
# Model evaluation using test_loader
model.eval() # set the model to evaluation mode
accuracy_list=[]

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    # Forward pass
    y_pred=model(batch_features)
    y_pred=(y_pred>0.5).float()  # Convert probabilities to binary prediction

    # Calculate accuracy for the current batch

    # batch_accuracy=(y_pred==batch_labels.view(-1,1)).float().mean().item()
    batch_accuracy=(y_pred.view(-1)==batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

  # Calculate overall accuracy
  overall_accuracy=sum(accuracy_list)/len(accuracy_list)
  print(f'Overall Accuracy: {overall_accuracy}')

Overall Accuracy: 0.9921875
