In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using cPU.")

GPU is available!
Using GPU: Tesla T4


**Creating a Tensor**

In [ ]:
# Using empty
a=torch.empty(2,3)

In [ ]:
# Check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2314, 0.6964, 0.2511],
        [0.6963, 0.1035, 0.8479]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.0515, 0.0699, 0.9184],
        [0.8208, 0.3699, 0.7717]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->",torch.arange(0,10,2))

# using linspace
print("using linspace ->",torch.linspace(0,10,10))

# using eye
print("using eye ->",torch.eye(5))

# using full
print("using full ->",torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[209363,      5,      5],
        [     5,      5,      5]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

# Mathematical Operations

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [ ]:
# addition
x+2
# substraction
x-2
# multiplication
x*3
# division
x/3
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

# Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [ ]:
# addition
a+b
# substraction
a-b
# multiplication
a*b
# division
a/b
# mod
a%b
# power
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reduction Operation

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e,dim=0)
# sum along rows
torch.sum(e,dim=1)

tensor([15., 13.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e,dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.min(e)
torch.max(e)

tensor(9.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [ ]:
# variance
torch.var(e)

tensor(9.8667)

In [ ]:
# argmax
torch.argmax(e)

tensor(3)

In [ ]:
# argmin
torch.argmin(e)

tensor(5)

# Matrix Operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[116, 153],
        [166, 225]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
f

tensor([[5, 7, 5],
        [9, 9, 7]])

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [ ]:
# determinant
torch.det(h)

tensor(-315.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

# Comparison Operations

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [ ]:
# greater than
i>j
# less than
i<j
# equal to
i==j
# not equal to
i!=j
# etc.

tensor([[True, True, True],
        [True, True, True]])

# Special functions

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[8., 5., 6.],
        [2., 9., 5.]])

In [ ]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [ ]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.9975, 0.0180, 0.7311],
        [0.0025, 0.9820, 0.2689]])

In [ ]:
# relu
torch.relu(k)

tensor([[8., 5., 6.],
        [2., 9., 5.]])

# Inplace Operations

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [ ]:
# use _(underscore) to done changes in current element
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [ ]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [ ]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [ ]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [ ]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [ ]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [ ]:
id(n)

134114164906320

In [ ]:
a=n

In [ ]:
id(a)

134114164906320

In [ ]:
a=n.clone()

In [ ]:
id(a)

134113934220480

# Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
b=a.to(device)

In [ ]:
b+5

tensor([[5.4175, 5.0340, 5.9157],
        [5.3079, 5.6269, 5.8277]], device='cuda:0')

In [ ]:
import time

# Define the size of the matrices
size=10000 # large size for performance comparison

# Create random matrices on CPU
matrix_cpu1=torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)

# Measure time on CPU
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2) # Matrix multiplication on CPUR
cpu_time = time.time()-start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')

# Measure time on GPU
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2) # Matrix multiplication on CPUR
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time()-start_time

print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):",cpu_time / gpu_time)

Time on CPU: 15.6816 seconds
Time on GPU: 0.6982 seconds

Speedup (CPU time / GPU time): 22.459571442815562


# Reshaping Tensors

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.1174, 0.6532, 0.5115, 0.3094],
         [0.7907, 0.7351, 0.2693, 0.8009],
         [0.5839, 0.0061, 0.4671, 0.8243]],

        [[0.2861, 0.7459, 0.8487, 0.4059],
         [0.2883, 0.2220, 0.6423, 0.7098],
         [0.5644, 0.4549, 0.0729, 0.8535]]])

In [ ]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
# image size
c=torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [ ]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# NumPy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])